version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge-browsers
    steps:
      - run:
          command: chromedriver
          background: true
      - checkout
      - run: sudo apt update
      - run: sudo apt upgrade
      - run:
          name: docker-compose build
          command: docker-compose build
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - run:
         name: wait for docker-compose up
         command: sleep 15
      - run:
          name: set db config for circleci
          command: mv config/database.ci.yml config/database.yml
      - run:
          name: db create
          command: docker-compose run web bundle exec rails db:create RAILS_ENV=test
      - run:
          name: db migrate
          command: docker-compose run web bundle exec rails db:migrate RAILS_ENV=test  
      - run:
          name: run rspec
          command: docker-compose run web bundle exec rspec spec
      - run:
          name: docker-compose down
          command: docker-compose down