version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: docker-compose build
          command: docker-compose build
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - run:
          name: db create
          command: docker-compose run web bundle exec rails db:create
      - run:
          name: db migrate
          command: docker-compose run web bundle exec rails db:migrate  
      - run:
          name: run rspec
          command: docker-compose run web bundle exec rspec spec
      - run:
          name: docker-compose down
          command: docker-compose down