version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: docker-compose build
          command: docker-compose build
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - run:
         name: wait for docker-compose up
         command: sleep 15
      - run:
         name: install chrome
         command: |
          sudo curl -sS -L https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list
          sudo apt-get update -q -y
          sudo apt-get install -y google-chrome-stable
      - run:
          name: set db config for circleci
          command: mv config/database.ci.yml config/database.yml
      - run:
          name: db create
          command: docker-compose run web bundle exec rails db:create RAILS_ENV=test
      - run:
          name: db migrate
          command: docker-compose run web bundle exec rails db:migrate RAILS_ENV=test  
      - run:
          name: run rspec
          command: docker-compose run web bundle exec rspec spec
      - run:
          name: docker-compose down
          command: docker-compose down